### ISSUE TITLE
cmke error

### ISSUE THREAD

**Issue by zih1998** [shamanDevel/fV-SRN#1]
$ : sh compile-library-server.sh
CMake
CMake Error: Unknown argument -RENDERER_BUILD_OPENGL_SUPPORT=OFF
CMake Error: Run 'cmake --help' for all supported options.
make: *** No targets specified and no makefile found.  Stop.
Setup-Tools build
No CUDA runtime is found, using CUDA_HOME=':/usr/local/cuda'
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    _arch_flags = _get_cuda_arch_flags()
  File "/home/dell/anaconda3/envs/fV/lib/python3.8/site-packages/torch/utils/cp_extension.py", line 1562, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
cp: cannot stat 'build/lib.linux-x86_64-3.8/pyrenderer.cpython-38-x86_64-linux-nu.so': No such file or directory
Test
compile-library-server.sh: 14: cd: can't cd to bin
1.9.1+cu102
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyrenderer'

**Comment by shamanDevel** [comment]
Hi, thanks for sharing this issue. There seem to be several issues. 
First, do you work on the latest commit? The error `Unknown argument -RENDERER_BUILD_OPENGL_SUPPORT=OFF` was fixed in one of the latest commits.
Second, it appears, you don't have the CUDA SDK installed. You need to install the CUDA SDK globally in order for CMake to detect it (`No CUDA runtime is found, using CUDA_HOME=':/usr/local/cuda'`). Also, I only support CUDA 11.0 or higher, so your PyTorch installation needs to match as well. Right now, you have version 1.9.1+cu102 installed, i.e. PyTorch links against the CUDA 10.2 runtime. This will crash during runtime or already during linking.

**Comment by zih1998** [comment]
> Hi, thanks for sharing this issue. There seem to be several issues. First, do you work on the latest commit? The error `Unknown argument -RENDERER_BUILD_OPENGL_SUPPORT=OFF` was fixed in one of the latest commits. Second, it appears, you don't have the CUDA SDK installed. You need to install the CUDA SDK globally in order for CMake to detect it (`No CUDA runtime is found, using CUDA_HOME=':/usr/local/cuda'`). Also, I only support CUDA 11.0 or higher, so your PyTorch installation needs to match as well. Right now, you have version 1.9.1+cu102 installed, i.e. PyTorch links against the CUDA 10.2 runtime. This will crash during runtime or already during linking.
Thanks a lot for your answer. I reconfigured the cuda environment as you suggested, but I now have some new problems and don't know how to fix it.  
**********************
CMake Error at CMakeLists.txt:151 (add_subdirectory):
  The source directory
    /home/dell/Code_zzh/fV-SRN/third-party/lz4
  does not contain a CMakeLists.txt file.
CMake Error at CMakeLists.txt:152 (set_property):
  set_property could not find TARGET lz4.  Perhaps it has not yet been
  created.
CMake Error at CMakeLists.txt:153 (set_target_properties):
  set_target_properties Can not find target to add properties to: lz4

CMake Error at CMakeLists.txt:155 (add_subdirectory):
  The source directory
    /home/dell/Code_zzh/fV-SRN/third-party/pybind11
  does not contain a CMakeLists.txt file.
CMake Error at bindings/CMakeLists.txt:10 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".
*****************************
See also "/home/Code/fV-SRN/build/CMakeFiles/CMakeOutput.log".
See also "/home/Code/fV-SRN/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
Setup-Tools build
arch flags: ['-gencode=arch=compute_86,code=compute_86', '-gencode=arch=compute_86,code=sm_86']
root path: /home/Code/fV-SRN
No resources found, did you run CMake beforehand?
cp: cannot stat 'build/lib.linux-x86_64-3.8/pyrenderer.cpython-38-x86_64-linux-gnu.so': No such file or directory
Test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dell/anaconda3/envs/fV/lib/python3.8/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
ImportError: libcudart-6d56b25a.so.11.0: cannot open shared object file: No such file or directory

**Comment by shamanDevel** [comment]
Hi, did you clone the repository with recursive submodules?

**Comment by zih1998** [comment]
> Hi, did you clone the repository with recursive submodules?

Hi, I have cloned submodules，and the previous issue has been resolved. But I have a new headache.
`subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.`

 I tried to modify it from 'ninja -v' to 'ninja --version', but the latter will report a g++ compilation error like the following,
`/usr/local/include/glm/ext/matrix_transform.inl:88:23: error: ‘qualifier’ has not been declared
   88 |  template<typename T, qualifier Q>
      |                       ^~~~~~~~~
/usr/local/include/glm/ext/matrix_transform.inl:89:21: error: ‘mat’ does not name a  type; did you mean ‘max’?
   89 |  GLM_FUNC_QUALIFIER mat<4, 4, T, Q> scale_slow(mat<4, 4, T, Q> const& m, vec     <3, T, Q> const& v)
      |                     ^~~
      |                     max
error: command '/usr/bin/g++' failed with exit code 1.
`
Some people say that the pytorch version needs to be downgraded.
My configuration environment is the same as you suggested except my system version.
Ubuntu 21.04, gcc 9.3.0, CUDA 11.1, Python 3.8, PyTorch 1.8

**Comment by zih1998** [comment]
> Hi, did you clone the repository with recursive submodules?

Hi, I have cloned submodules，and the previous issue has been resolved. But I have a new headache.
*********
`/usr/local/include/glm/ext/matrix_transform.inl:88:23: error: ‘qualifier’ has not been declared.
88 | template<typename T, qualifier Q> | ^~~~~~~~~ 
/usr/local/include/glm/ext/matrix_transform.inl:89:21: error: ‘mat’ does not name a type; did you mean ‘max’? 
89 | GLM_FUNC_QUALIFIER mat<4, 4, T, Q> scale_slow(mat<4, 4, T, Q> const& m, vec <3, T, Q> const& v) | ^~~ | max 
........................
........
`
***************
`ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/fV/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/dell/anaconda3/envs/fV/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.`
*******************
I tried to modify it from 'ninja -v' to 'ninja --version', but the latter will report a g++ compilation error like the following,
`error: command '/usr/bin/g++' failed with exit code 1.`

Some people say that the pytorch version needs to be downgraded.
My configuration environment is the same as you suggested except my system version.
Ubuntu 21.04, gcc 9.3.0, CUDA 11.1, Python 3.8, PyTorch 1.8

**Comment by shamanDevel** [comment]
This seems to be an error in GLM. But without a complete stack trace, I can't tell you if the error happens due to an problem in the GLM internals or how I use GLM in my code.
For reference, `apt list | grep 'glm'` tells me, I have GLM version `0.9.9.7+ds-1` installed on my Ubuntu machine.

**Comment by zih1998** [comment]
> 0.9.9.7+ds-1

glmark2-data/hirsute-updates,hirsute-updates 2021.02-0ubuntu1~21.04.1 all
glmark2-drm/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2-drm/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2-wayland/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-wayland/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmemperf-data/hirsute,hirsute 0.17-0ubuntu4 all
glmemperf/hirsute 0.17-0ubuntu4 amd64
libcglm-dev/hirsute 0.7.9-1 amd64
libcglm-doc/hirsute,hirsute 0.7.9-1 all
libcglm0/hirsute 0.7.9-1 amd64
libglm-dev/hirsute,hirsute,now 0.9.9.8+ds-1 all [installed]
libglm-doc/hirsute,hirsute 0.9.9.8+ds-1 all
r-bioc-glmgampoi/hirsute 1.2.0+dfsg-6 amd64
r-cran-brglm/hirsute 0.7.1-1 amd64
r-cran-glmmtmb/hirsute 1.0.2.1-1 amd64
r-cran-glmnet/hirsute 4.1-1 amd64
r-cran-randomglm/hirsute 1.02-1-1build1 amd64

**Comment by zih1998** [comment]
> This seems to be an error in GLM. But without a complete stack trace, I can't tell you if the error happens due to an problem in the GLM internals or how I use GLM in my code. For reference, `apt list | grep 'glm'` tells me, I have GLM version `0.9.9.7+ds-1` installed on my Ubuntu machine.

`glmark2-data/hirsute-updates,hirsute-updates 2021.02-0ubuntu1~21.04.1 all
glmark2-drm/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2-drm/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2-wayland/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-wayland/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmemperf-data/hirsute,hirsute 0.17-0ubuntu4 all
glmemperf/hirsute 0.17-0ubuntu4 amd64
libcglm-dev/hirsute 0.7.9-1 amd64
libcglm-doc/hirsute,hirsute 0.7.9-1 all
libcglm0/hirsute 0.7.9-1 amd64
libglm-dev/hirsute,hirsute,now 0.9.9.8+ds-1 all [installed]
libglm-doc/hirsute,hirsute 0.9.9.8+ds-1 all
r-bioc-glmgampoi/hirsute 1.2.0+dfsg-6 amd64
r-cran-brglm/hirsute 0.7.1-1 amd64
r-cran-glmmtmb/hirsute 1.0.2.1-1 amd64
r-cran-glmnet/hirsute 4.1-1 amd64
r-cran-randomglm/hirsute 1.02-1-1build1 amd64
`

**Comment by zih1998** [comment]
> This seems to be an error in GLM. But without a complete stack trace, I can't tell you if the error happens due to an problem in the GLM internals or how I use GLM in my code. For reference, `apt list | grep 'glm'` tells me, I have GLM version `0.9.9.7+ds-1` installed on my Ubuntu machine.

glmark2-data/hirsute-updates,hirsute-updates 2021.02-0ubuntu1~21.04.1 all
glmark2-drm/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2-drm/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2-wayland/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-es2/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2-wayland/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmark2/hirsute-updates 2021.02-0ubuntu1~21.04.1 amd64
glmemperf-data/hirsute,hirsute 0.17-0ubuntu4 all
glmemperf/hirsute 0.17-0ubuntu4 amd64
libcglm-dev/hirsute 0.7.9-1 amd64
libcglm-doc/hirsute,hirsute 0.7.9-1 all
libcglm0/hirsute 0.7.9-1 amd64
libglm-dev/hirsute,hirsute,now 0.9.9.8+ds-1 all [installed]
libglm-doc/hirsute,hirsute 0.9.9.8+ds-1 all
r-bioc-glmgampoi/hirsute 1.2.0+dfsg-6 amd64
r-cran-brglm/hirsute 0.7.1-1 amd64
r-cran-glmmtmb/hirsute 1.0.2.1-1 amd64
r-cran-glmnet/hirsute 4.1-1 amd64
r-cran-randomglm/hirsute 1.02-1-1build1 amd64
**********************************************************************
After some modification, errors in glm still exist and now the traceback shows like this.
Test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dell/anaconda3/envs/fV/lib/python3.8/site-packages/torch/__init_ 196, in <module>
    from torch._C import *
ImportError: libcudart-6d56b25a.so.11.0: cannot open shared object file: No sudirectory

**Comment by shamanDevel** [comment]
Sorry, this does not help me at all. I need the full console log from `make` and `sh compile_library_server.sh`

**Comment by zih1998** [comment]
> Sorry, this does not help me at all. I need the full console log from `make` and `sh compile_library_server.sh`
[Output.txt](https://github.com/shamanDevel/fV-SRN/files/8113352/Output.txt)
This is my output log.

**Comment by shamanDevel** [comment]
Hi zih1998, is there an update in this regard?
From the error above, it seems that the compilation of my library is successful, but PyTorch itself can't be loaded due to missing libcudart (wrong CUDA installation?)

**Comment by zih1998** [comment]
> Hi zih1998, is there an update in this regard? From the error above, it seems that the compilation of my library is successful, but PyTorch itself can't be loaded due to missing libcudart (wrong CUDA installation?)
Hi, I think my cuda version is correct, but every time I get various compilation errors or other errors caused by missing packages. But tonight I reconfigured the environment, and finally the import was successful, haha...  :D
My coding skills are a bit poor, I'm in my second year of master's and it looks like I have a long way to go. :C

**Comment by shamanDevel** [comment]
No worries, such a fused C++ / CUDA / Python project is not the easiest to set up. It took me a while to get it running at the start as well ^^.
But does it work now for you? Then I would close the issue.

**Comment by zih1998** [comment]
> No worries, such a fused C++ / CUDA / Python project is not the easiest to set up. It took me a while to get it running at the start as well ^^. But does it work now for you? Then I would close the issue.

Yes, now the import is successful, you could close the issue.

**Comment by shamanDevel** [comment]
Ok, then good luck with your project and if you have further questions, just mail me or open another issue.

**Comment by zih1998** [comment]
> Ok, then good luck with your project and if you have further questions, just mail me or open another issue.
Alright, thank you very much
